# Generated by Django 3.1.3 on 2020-11-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_readed',
        ),
        migrations.RemoveField(
            model_name='message',
            name='pub_date',
        ),
    ]
