# Generated by Django 3.1.3 on 2020-11-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20201114_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
